Change category
devhausleipzig/camp8-final-project pull request #109
Opened 2023-03-02 14:50 UTC by amyria3

The point must receive:
  item_id
  target_category_id
as request-body.
It will then pick then update the  customCategoryId of Item

2023-03-07 15:27 UTC, NoHara42 requested changes
see small change

2023-03-16 07:31 UTC, amyria3 commented on src/pages/api/changeCategory.ts
> +const prisma = new PrismaClient();
done

2023-03-21 17:21 UTC, RealBirdMan91 requested changes
looks good =)

But you don't need that one 

```TS
else {
    response
      .status(404)
      .send(
        `Invalid method in a front-end-script, need a PATCH to update the category, request method was ${request.method}`
      );
  }
```

2023-03-23 12:15 UTC, amyria3 commented
done

2023-03-24 10:30 UTC, RealBirdMan91 approved these changes

2023-03-24 10:33 UTC, merged