List with cards
devhausleipzig/camp8-final-project pull request #180
Opened 2023-03-29 08:00 UTC by RealBirdMan91

User and List have to be linked together

2023-03-29 16:13 UTC, amyria3 commented
Authentification seems to work

2023-03-30 08:48 UTC, NoHara42 commented on package.json
> +    "prisma": "4.12.0-dev.34",
in other words, please put this back to the previous version unless there is an explicit reason - dev releases aren't normally stable.

2023-03-30 08:49 UTC, NoHara42 commented on src/components/Lists.tsx
delete this please

2023-03-30 09:00 UTC, NoHara42 commented on src/pages/api/createList.ts
>  /* The point gets user id and should take name, if
??

2023-03-30 09:21 UTC, NoHara42 commented on src/stories/Card.stories.tsx
> +import Card from "../components/SingleCard";
Card should be SingleCard here right?

2023-03-30 09:23 UTC, NoHara42 requested changes
see small changes

2023-03-30 10:14 UTC, iameru commented
Please recheck, all changes requested are done, except for storybook which I reverted to show the originial `Card` component

2023-03-30 11:41 UTC, NoHara42 commented
@iameru 

Issues:
- when you delete a list item you get an error
- when you drag a list item when inspecting on desktop dimensions, you immediately enter the list items
- User name is not displayed instead of the "Hey Beautiful" placeholder
- Draft lists (lists that have just been created) are not greyed out, and have "NEW LIST" as a default value. 
(A user should not have to remove "NEW LIST" to enter their list name.

- See design issues at iPhone SE dimensions 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43496778/228824796-7c1630bc-882a-482c-9cd0-766b7d567f1c.png">

2023-03-31 03:43 UTC, merged