linked icon to account/settings page
devhausleipzig/camp8-final-project pull request #185
Opened 2023-03-29 15:51 UTC by Regi-Rexus

2023-03-29 16:16 UTC, NoHara42 commented on src/pages/home/index.tsx
> -// import { UserCircleIcon } from "@heroicons/react/24/outline";
please remove instead of commenting out here

2023-03-29 16:20 UTC, NoHara42 commented on src/pages/home/index.tsx
> -        <div className=" flex flex-row justify-between h-12 mt-4">
this div can be removed

2023-03-29 16:25 UTC, NoHara42 requested changes
see changes :)

2023-03-30 11:56 UTC, Regi-Rexus commented
sorry Ned, it was me who was using too big spacing! I changed it to 2 now

2023-03-30 16:23 UTC, NoHara42 approved these changes
LGTM

2023-03-30 16:23 UTC, merged