Add item
devhausleipzig/camp8-final-project pull request #50
Opened 2023-02-21 09:45 UTC by TheDoplarEffect

2023-02-21 09:49 UTC, TheDoplarEffect commented
Main Additions are in pages/api/addItems.ts file

The point of this endpoint is to add an item to a list (someone has typed in and pressed enter).
First check the name given against the database.
Since there are multiple ways to spell something we are trying to remove  a couple of letters at a time and see if there is a match
When shorter than 3 letters we just put it in the Other list

2023-02-21 13:08 UTC, NoHara42 commented on tsconfig.json
> +    "module": "commonjs",
you cannot parse the entire project as if it were nodejs, as the rest runs on the browser.

If you need to run code on the server, provide a `tsconfig.json` with `"module": "commonjs"` in the same folder as your server files, keeping the root `tsconfig.json` its original value

2023-02-21 13:10 UTC, NoHara42 requested changes
reverse merge before PR, also see comments @TheDoplarEffect

2023-02-21 13:12 UTC, NoHara42 commented on .env
> +# Environment variables declared in this file are automatically made available to Prisma.
git rm --cached name_of_file

2023-02-23 13:15 UTC, NoHara42 commented on .env
> +# Environment variables declared in this file are automatically made available to Prisma.
file is still committed... @TheDoplarEffect

2023-02-23 13:17 UTC, NoHara42 commented on tsconfig.json
> +    "module": "commonjs",
module is still `commonjs` here

2023-02-23 13:18 UTC, NoHara42 requested changes
please don't commit .env or lock files, also see unadapted amendments

2023-02-23 13:20 UTC, NoHara42 approved these changes
LGTM!

2023-02-23 13:54 UTC, merged