29 search bar component
devhausleipzig/camp8-final-project pull request #60
Opened 2023-02-22 15:09 UTC by ArthiRagothaman

2023-02-23 15:32 UTC, NoHara42 commented on src/components/SearchBar.tsx
> +										{selected ? (
no need for ternary here, use the `&&` operator.
see:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND#short-circuit_evaluation

2023-02-23 15:33 UTC, NoHara42 commented on src/components/SearchBar.tsx
> +										active ? "bg-teal-600 text-white" : " "
see below comment

2023-02-23 15:40 UTC, NoHara42 requested changes
please remove lock files and merge main into your branch before asking for a review @ArthiRagothaman

2023-03-01 11:45 UTC, NoHara42 commented on src/components/SearchBar.tsx
> +											: " "
looks like a use-case for `&&` , see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND#short-circuit_evaluation

2023-03-01 11:47 UTC, NoHara42 requested changes
see changes, also the dropdown list of options doesn't match what design has requested, the list of options is not in-line with the searchbar
@ArthiRagothaman 
![image](https://user-images.githubusercontent.com/43496778/222130774-f3be6c67-0a7b-4a6a-9993-1e404b18bbc2.png)

2023-03-01 21:49 UTC, ArthiRagothaman commented
As requested updated the changes

2023-03-02 14:21 UTC, NoHara42 requested changes
comment from previous review not resolved, see edge case in screenshot below
- (x) text goes under icon when long enough
- (x) storybook does not have disabled variant, nor disabled control for the disabled state seen in the mockup

![image](https://user-images.githubusercontent.com/43496778/222454102-c58b3d80-945f-45ab-b629-b58f4b42204d.png)

2023-03-02 21:16 UTC, ArthiRagothaman commented
- input contains padding so that the text does not go over the icon when it is long enough
1.  Even after removed the padding it didn't work. Yes, it will go over the icon. The issue will get resolved only if the icon changed to left side.
(Drop down list restricts to choose one of the options for user so no need to type so long)

- storybook has disabled variant, with disabled control for the disabled state seen in the mockup

2. This is not my component. There is separate home component for those disable variant [home](https://www.figma.com/file/MwSsIVfA5KQIZCdhIcASnC/Grocery-App?node-id=65%3A132&t=O6xM2HbvfXx8xfGj-4)

2023-03-03 13:36 UTC, ArthiRagothaman commented
- [ ]  Now Text will not overlap the icon seems working
- [ ]  updated the styles 
- [ ]  Not clear about the disabled variant

2023-03-07 14:41 UTC, NoHara42 requested changes
heroicons have not been added to this branches `package.json` file as a dependency.

Therefore I unfortunately cannot test this branch

2023-03-09 14:02 UTC, ArthiRagothaman commented
Now icons will update as per [Update icons](https://github.com/devhausleipzig/camp8-final-project/issues/119) this link.
I have included feather icons in my component.

2023-03-10 15:40 UTC, merged