Image api research
devhausleipzig/camp8-final-project pull request #61
Opened 2023-02-23 08:39 UTC by TheDoplarEffect

Found an API and reconstructed the original Database with array of objects that also have images.

A lot of the items (all non food) were not detectected.  But a solid 60% now how similar images.
This can be updated later on.

2023-02-27 10:34 UTC, TheDoplarEffect commented
Just waiting for new version of schema to be approved.

2023-03-01 14:41 UTC, TheDoplarEffect commented
This PR gives more info on the original Database (Images).
Fixes the seed file to account for new Database.
Also fixees the addItem endpoint since that had already been merged into main.

2023-03-03 12:39 UTC, NoHara42 commented on src/pages/index.tsx
> +import Image from "next/image";
unused import

2023-03-03 12:51 UTC, NoHara42 commented on src/pages/api/addItem.ts
>  const prisma = new PrismaClient();
see https://github.com/devhausleipzig/camp8-final-project/pull/100#discussion_r1123218794

2023-03-03 12:55 UTC, NoHara42 commented on src/pages/api/addItem.ts
>      try {
please try handling all the errors without nested try/catch blocks, handle all the errors in the parent catch block

2023-03-03 12:56 UTC, NoHara42 requested changes
please merge Niels' changes onto this branch
https://github.com/devhausleipzig/camp8-final-project/pull/100

and see suggestions

2023-03-03 12:58 UTC, NoHara42 commented
love the commit messages by the way

2023-03-07 14:49 UTC, NoHara42 approved these changes
LGTM

2023-03-07 14:50 UTC, merged